
name: Student Project Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-project:
    runs-on: ubuntu-latest

    steps:
      - name: Get project code
        uses: actions/checkout@v4

      - name: Check required files
        run: |
          test -f index.html
          test -f style.css
          test -f script.js
          echo "All required project files are present."
